# Generated by Django 6.0 on 2025-12-29 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.CharField(help_text='Введите уникальный идентификатор поставки', max_length=64, primary_key=True, serialize=False, verbose_name='ID поставки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acts.store', verbose_name='Магазин получатель поставки')),
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acts.store', verbose_name='Магазин плательщик')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
