# Generated by Django 6.0 on 2026-01-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Дата начала промежутка')),
                ('period_end', models.DateField(verbose_name='Дата конца промежутка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания акта сверки')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act', to='acts.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'акт сверки',
                'verbose_name_plural': 'Акты сверки',
            },
        ),
    ]
