# Generated by Django 6.0 on 2025-12-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply', to='acts.store', verbose_name='Магазин получатель поставки'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='acts.store', verbose_name='Магазин плательщик'),
        ),
    ]
