# Generated by Django 6.0 on 2026-01-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='notes',
            field=models.CharField(blank=True, null=True, verbose_name='Заметки'),
        ),
    ]
