# Generated by Django 6.0 on 2025-12-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_alter_supply_store_alter_transaction_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconiliationAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Дата начала промежутка')),
                ('period_end', models.DateField(verbose_name='Дата конца промежутка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания акта сверки')),
                ('stores', models.ManyToManyField(related_name='reconciliation_acts', to='acts.store', verbose_name='Магазины')),
            ],
        ),
    ]
