# Generated by Django 6.0.2 on 2026-03-16 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0003_store_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ('date',), 'verbose_name': 'поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('date',), 'verbose_name': 'платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AddField(
            model_name='supply',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supply',
            name='date',
            field=models.DateField(verbose_name='Дата поставки'),
        ),
    ]
