# Generated by Django 6.0 on 2025-12-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0003_reconiliationact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='date',
            field=models.DateField(help_text='Формат день.месяц.год', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ID поставки'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата транзакции'),
        ),
    ]
