# Generated by Django 6.0.2 on 2026-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0004_alter_store_options_alter_supply_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='supply',
            name='tags',
            field=models.ManyToManyField(blank=True, to='acts.tag', verbose_name='Метки'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, to='acts.tag', verbose_name='Метки'),
        ),
    ]
