# Generated by Django 6.0 on 2025-12-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0004_alter_supply_date_alter_supply_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Дата транзакции'),
        ),
    ]
