# Generated by Django 6.0 on 2025-12-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0005_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconiliationact',
            options={'verbose_name': 'акт сверки', 'verbose_name_plural': 'Акты сверки'},
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=264, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
