# Generated by Django 6.0.2 on 2026-04-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0005_tag_supply_tags_transaction_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ('-date',), 'verbose_name': 'поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'метка', 'verbose_name_plural': 'Метки'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date',), 'verbose_name': 'платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
