# Generated by Django 6.0.2 on 2026-07-06 18:05

import acts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0006_alter_supply_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[acts.models.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
